name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v6

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build project
        env:
          STORE_FILE: dev.p12
          STORE_PASSWORD: ${{ secrets.STORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        run: |
          echo "${{ secrets.STORE_FILE }}" | base64 --decode > app/dev.p12
          ./gradlew build
          ./gradlew bundle

      - name: Lint project
        run: ./gradlew lint lintRelease

      - name: Upload debug APKs
        uses: actions/upload-artifact@v7
        with:
          name: debug-apks
          path: app/build/outputs/apk/debug/*.apk

      - name: Upload release APKs
        uses: actions/upload-artifact@v7
        with:
          name: release-apks
          path: app/build/outputs/apk/release/*.apk

      - name: Upload debug AABs
        uses: actions/upload-artifact@v7
        with:
          name: debug-aabs
          path: app/build/outputs/bundle/debug/*.aab

      - name: Upload release AABs
        uses: actions/upload-artifact@v7
        with:
          name: release-aabs
          path: app/build/outputs/bundle/release/*.aab

      - name: Upload mapping
        uses: actions/upload-artifact@v7
        with:
          name: mapping
          path: app/build/outputs/mapping/release/*.txt

      - name: Upload logs
        uses: actions/upload-artifact@v7
        with:
          name: logs
          path: app/build/outputs/logs/*.txt

      - name: Upload lint reports
        uses: actions/upload-artifact@v7
        with:
          name: reports
          path: app/build/reports/*

      - name: Generate build provenance attestations
        uses: actions/attest-build-provenance@v4
        with:
          subject-path: |
            app/build/outputs/apk/**/*.apk
            app/build/outputs/bundle/**/*.aab
            app/build/outputs/native-debug-symbols/release/*.zip
            app/build/outputs/mapping/release/*.txt
            app/build/outputs/logs/*.txt
            app/build/reports/*
